version: "3.9"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"                   # Web UI Jenkins
      - "50000:50000"                 # For agent connections
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-kubeconfig:/var/jenkins_home/.kube/config
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_home:
